spring.application.name=dijital-jeoloji-muze-backend
server.port=8080

spring.data.mongodb.uri=mongodb+srv://dbUser:dbUserPassword@dev-cluster.q2jpkd1.mongodb.net/djm_db?retryWrites=true&w=majority
spring.data.mongodb.database=djm_db

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
